##ServerConsole Properties
serverTitle=cids Domainserver (BELIS2)
serverClass=Sirius.server.middleware.impls.domainserver.DomainServerImpl
log4jConfig=runtime.properties
log4j_prop_file=runtime.properties
managementRoot=.
webserverPort=8023
serverConsole.friends=http://s10221:7022/cidsservermanager, cidsRegistry @ s10221; http://s10221:7023/cidsservermanager, cidsBroker @ s10221; http://s10221:7024/cidsservermanager, WuNDa live @ s10221;http://s10221:7082/cidsservermanager, GrundIS @ s10221;http://s10221:7026/cidsservermanager, LagIS @ s10221
serverConsole.Logfiles=ServerLog.html 

webserverInterfaceConfig=runtime.properties
runtimeArgs=runtime.properties

## server.config
startMode=simple
serverName=BELIS2
serverPort=

serverPolicy=WIKI
classNodePolicy=STANDARD
pureNodePolicy=WIKI
attributePolicy=STANDARD

rmiRegistryPort=1099
server.rest.enable=true
server.rest.debug=true
server.rest.port=9917
connection.driver_class=org.postgresql.Driver
connection.username=postgres
#connection.username=belis
connection.password=r102.341
#connection.url=jdbc:postgresql://localhost:5432/mirror_belis
connection.url=jdbc:postgresql://localhost:5435/belis
connection.pool_size=5
dialect=org.hibernate.dialect.PostgreSQLDialect
iconDirectory=./icons
defaultIconDirectory=./icons
queryStoreDirectory=./querystore
fileSeparator=/
registryIPs=localhost
quotedTypes=1;3;45;47;71;25;29;78;79;80;81;82;180;269

## miniServer.properties
AliasesDefinitionFile_option=-a
AliasesDefinitionFile_value=runtime.properties
ServletPropertiesFile_option=-s
ServletPropertiesFile_value=runtime.properties
LogOption=-l
LogOption_value=n
LogOutputDirectory=./
SessionTimeOutInMinutesOption=-e
SessionTimeOutInMinutesValue=-60

##servlet.properties
servlet./cidsservermanager.code=de.cismet.cids.admin.serverManagement.servlet.ServerManager
servlet./fileeditor.code=de.cismet.cids.admin.serverManagement.servlet.FileEditorServlet
servlet./serverlogfile.code=de.cismet.cids.admin.serverManagement.servlet.ServerLogFile

##log4jproperties
log4j_prop_file=runtime.properties

log4j.rootLogger=ERROR,standardOut
log4j.rootLogger=ERROR,logfile
#log4j.rootLogger=DEBUG,beanmill
#log4j.rootLogger=INFO,beanmill
log4j.rootLogger=ERROR,beanmill

# Appender
#STDOUT
log4j.appender.standardOut=org.apache.log4j.ConsoleAppender
log4j.appender.standardOut.layout=org.apache.log4j.PatternLayout
log4j.appender.standardOut.layout.ConversionPattern=%-5p [%t] - %m%n

# File
log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.file=./serverLog.txt
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - %m%n
log4j.appender.logfile.append=true
log4j.appender.logfile.MaxFileSize=15MB
log4j.appender.logfile.MaxBackupIndex=5

#Socket
log4j.appender.beanmill=org.apache.log4j.net.SocketAppender
log4j.appender.beanmill.remoteHost=localhost
log4j.appender.beanmill.port=4445
log4j.appender.beanmill.locationInfo=true

