DROP VIEW IF EXISTS textsearch CASCADE;
DROP VIEW IF EXISTS geosuche CASCADE;
DROP VIEW IF EXISTS cs_class_hierarchy CASCADE;
DROP TABLE IF EXISTS cs_config_attr_exempt CASCADE; DROP SEQUENCE IF EXISTS cs_config_attr_exempt_sequence CASCADE;
DROP TABLE IF EXISTS cs_config_attr_jt CASCADE; DROP SEQUENCE IF EXISTS cs_config_attr_jt_sequence CASCADE;
DROP TABLE IF EXISTS cs_config_attr_key CASCADE; DROP SEQUENCE IF EXISTS cs_config_attr_key_sequence CASCADE;
DROP TABLE IF EXISTS cs_config_attr_value CASCADE; DROP SEQUENCE IF EXISTS cs_config_attr_value_sequence CASCADE;
DROP TABLE IF EXISTS cs_config_attr_type CASCADE; DROP SEQUENCE IF EXISTS cs_config_attr_type_sequence CASCADE;
DROP TABLE IF EXISTS cs_attr_object CASCADE;
DROP TABLE IF EXISTS cs_attr_object_derived CASCADE;
DROP TABLE IF EXISTS cs_attr CASCADE; DROP SEQUENCE IF EXISTS cs_attr_sequence CASCADE;
DROP TABLE IF EXISTS cs_attr_string CASCADE;
DROP TABLE IF EXISTS cs_cat_link CASCADE; DROP SEQUENCE IF EXISTS cs_cat_link_sequence CASCADE;
DROP TABLE IF EXISTS cs_cat_node CASCADE; DROP SEQUENCE IF EXISTS cs_cat_node_sequence CASCADE;
DROP TABLE IF EXISTS cs_history CASCADE;
DROP TABLE IF EXISTS cs_class CASCADE; DROP SEQUENCE IF EXISTS cs_class_sequence CASCADE;
DROP TABLE IF EXISTS cs_class_attr CASCADE; DROP SEQUENCE IF EXISTS cs_class_attr_sequence CASCADE;
DROP TABLE IF EXISTS cs_domain CASCADE; DROP SEQUENCE IF EXISTS cs_domain_sequence CASCADE;
DROP TABLE IF EXISTS cs_icon CASCADE; DROP SEQUENCE IF EXISTS cs_icon_sequence CASCADE;
DROP TABLE IF EXISTS cs_java_class CASCADE; DROP SEQUENCE IF EXISTS cs_java_class_sequence CASCADE;
DROP TABLE IF EXISTS cs_locks CASCADE; DROP SEQUENCE IF EXISTS cs_locks_seq CASCADE;
DROP TABLE IF EXISTS cs_method CASCADE; DROP SEQUENCE IF EXISTS cs_method_sequence CASCADE;
DROP TABLE IF EXISTS cs_method_class_assoc CASCADE; DROP SEQUENCE IF EXISTS cs_method_class_assoc_sequence CASCADE;
DROP TABLE IF EXISTS cs_permission CASCADE; DROP SEQUENCE IF EXISTS cs_permission_sequence CASCADE;
DROP TABLE IF EXISTS cs_policy CASCADE; DROP SEQUENCE IF EXISTS cs_policy_sequence CASCADE;
DROP TABLE IF EXISTS cs_policy_rule CASCADE; DROP SEQUENCE IF EXISTS cs_policy_rule_sequence CASCADE;
DROP TABLE IF EXISTS cs_query CASCADE; DROP SEQUENCE IF EXISTS cs_query_sequence CASCADE;
DROP TABLE IF EXISTS cs_query_class_assoc CASCADE; DROP SEQUENCE IF EXISTS cs_query_class_assoc_sequence CASCADE;
DROP TABLE IF EXISTS cs_query_link CASCADE; DROP SEQUENCE IF EXISTS cs_query_link_sequence CASCADE;
DROP TABLE IF EXISTS cs_query_parameter CASCADE; DROP SEQUENCE IF EXISTS cs_query_parameter_sequence CASCADE;
DROP TABLE IF EXISTS cs_query_store CASCADE; DROP SEQUENCE IF EXISTS cs_query_store_sequence CASCADE;
DROP TABLE IF EXISTS cs_query_store_ug_assoc CASCADE; DROP SEQUENCE IF EXISTS cs_query_store_ug_assoc_sequence CASCADE;
DROP TABLE IF EXISTS cs_query_ug_assoc CASCADE; DROP SEQUENCE IF EXISTS cs_query_ug_assoc_sequence CASCADE;
DROP TABLE IF EXISTS cs_type CASCADE; DROP SEQUENCE IF EXISTS cs_type_sequence CASCADE;
DROP TABLE IF EXISTS cs_ug CASCADE; DROP SEQUENCE IF EXISTS cs_ug_sequence CASCADE;
DROP TABLE IF EXISTS cs_ug_attr_perm CASCADE; DROP SEQUENCE IF EXISTS cs_ug_attr_perm_sequence CASCADE;
DROP TABLE IF EXISTS cs_ug_cat_node_perm CASCADE; DROP SEQUENCE IF EXISTS cs_ug_cat_node_perm_sequence CASCADE;
DROP TABLE IF EXISTS cs_ug_class_perm CASCADE; DROP SEQUENCE IF EXISTS cs_ug_class_perm_sequence CASCADE;
DROP TABLE IF EXISTS cs_ug_membership CASCADE; DROP SEQUENCE IF EXISTS cs_ug_membership_sequence CASCADE;
DROP TABLE IF EXISTS cs_ug_method_perm CASCADE; DROP SEQUENCE IF EXISTS cs_ug_method_perm_sequence CASCADE;
DROP TABLE IF EXISTS cs_usr CASCADE; DROP SEQUENCE IF EXISTS cs_usr_sequence CASCADE;
DROP TABLE IF EXISTS geom CASCADE; DROP SEQUENCE IF EXISTS geom_seq CASCADE;
DROP TABLE IF EXISTS url_base CASCADE; DROP SEQUENCE IF EXISTS url_base_seq CASCADE;
DROP TABLE IF EXISTS url CASCADE; DROP SEQUENCE IF EXISTS url_seq CASCADE;
DROP TABLE IF EXISTS cs_changed CASCADE;
DROP TABLE IF EXISTS cs_scheduled_serveractions CASCADE; DROP SEQUENCE IF EXISTS cs_scheduled_serveractions_sequence CASCADE;
DROP TABLE IF EXISTS cs_cache CASCADE;
DROP TABLE IF EXISTS cs_dynamic_children_helper CASCADE; DROP SEQUENCE IF EXISTS cs_dynamic_children_helper_sequence CASCADE;
DROP FUNCTION IF EXISTS insert_cache_entry(classid integer, objectId integer) CASCADE;
DROP FUNCTION IF EXISTS recreate_cache() CASCADE;
DROP FUNCTION IF EXISTS recreate_cache(classid integer) CASCADE;
DROP FUNCTION IF EXISTS recreate_cache(tablename text) CASCADE;
DROP FUNCTION IF EXISTS insert_cache_entry(tableName text, objectId integer) CASCADE;
DROP FUNCTION IF EXISTS update_cache_entry(tableName text, objectId integer) CASCADE;
DROP FUNCTION IF EXISTS reindexpure(classid integer) CASCADE;
DROP FUNCTION IF EXISTS reindexderivedobjects(classid integer) CASCADE;
DROP FUNCTION IF EXISTS reindex() CASCADE;
DROP FUNCTION IF EXISTS reindex(class_id integer) CASCADE;
DROP FUNCTION IF EXISTS reindexpure(classid integer, objectid integer) CASCADE;
DROP FUNCTION IF EXISTS salt(integer) CASCADE;
DROP FUNCTION IF EXISTS cidsObjectExists(cid integer, oid integer) CASCADE;
DROP FUNCTION IF EXISTS execute(_command text) CASCADE;
DROP FUNCTION IF EXISTS selexecute(_command text) CASCADE;
DROP FUNCTION IF EXISTS execute_query(_command text) CASCADE;
DROP FUNCTION IF EXISTS public.cs_refresh_changed() CASCADE;
DROP FUNCTION IF EXISTS public.cs_refresh_changed(classId integer) CASCADE;
-- DROP FUNCTION IF EXISTS cs_recreatecacheddaqview(text) CASCADE;
DROP FUNCTION IF EXISTS cs_recreatecacheddaqview(viewname text) CASCADE;
